## 学习内容

### Exception()

### Try、throw 和 catch




``` 
<?php
// 创建一个有异常处理的函数
function error($number)
{
    if($number>1)
    {
        throw new \Exception("传的参数必须小于等于1");
    }
    return true;
}

// 触发异常
error(2);

?>

```
#### Try、throw 和 catch
> 要避免上面实例中出现的错误，我们需要创建适当的代码来处理异常。

> 适当的处理异常代码应该包括：

* Try - 使用异常的函数应该位于 "try" 代码块内。如果没有触发异常，则代码将照常继续执行。但是如果异常被触发，会抛出一个异常。
* Throw - 里规定如何触发异常。每一个 "throw" 必须对应至少一个 "catch"。
* Catch - "catch" 代码块会捕获异常，并创建一个包含异常信息的对象。


``` 
<?php
// 创建一个有异常处理的函数
function error($number)
{
    if($number>1)
    {
        throw new Exception("传的参数必须小于等于1");
    }
    return true;
}

// 在 try 块 触发异常
try
{
    error(1);
    // 如果抛出异常，以下文本不会输出
    echo '正常输出';
}
// 捕获异常
catch(Exception $e)
{
    echo 'Message: ' .$e->getMessage();
}
?>

```


#### 类的实战，自定义异常类 

``` 
<?php
class customException extends Exception
{
    public function errorMessage()
    {
        // 错误信息
        $errorMsg = '错误行号 '.$this->getLine().' in '.$this->getFile()
            .': <b>'.$this->getMessage().'</b> 不是一个合法的 E-Mail 地址';
        return $errorMsg;
    }
}

$email = "someone@example...com";

try
{
    // 检测邮箱
    if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE)
    {
        // 如果是个不合法的邮箱地址，抛出异常
        throw new customException($email);
    }
}

catch (customException $e)
{

echo $e->errorMessage();
}
?>


```
